spring.application.name=paidou
# === Base de données ===
spring.datasource.url=jdbc:postgresql://localhost:5432/paidou_db
spring.datasource.username=paidou_user
spring.datasource.password=paidou_password
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Port du serveur ===
server.port=8080