spring.application.name=paidou
# === Base de données ===
spring.datasource.url=jdbc:postgresql://ep-square-resonance-aliquwrp.c-3.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_M2jwQfbd8umI

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === Port du serveur ===
server.port=8080